package br.com.xml.tftp.exemplo;

public class Xml {
	public String xmlContent() {

		return "<device>\r\n" + "<deviceProtocol>SIP</deviceProtocol> \r\n" + "<sshUserId></sshUserId>  \r\n"
				+ "<sshPassword></sshPassword> \r\n" + "<devicePool>  \r\n" + " <dateTimeSetting>  \r\n"
				+ "    <dateTemplate>D/M/Y</dateTemplate>  \r\n"
				+ "    <timeZone>SA Eastern Standard Time</timeZone>\r\n" + "    <ntps>  \r\n" + "         <ntp>  \r\n"
				+ "             <name>200.160.0.8</name>  \r\n" + "             <ntpMode>Unicast</ntpMode>  \r\n"
				+ "         </ntp>  \r\n" + "    </ntps>  \r\n" + " </dateTimeSetting>  \r\n"
				+ " <callManagerGroup>  \r\n" + "    <members>  \r\n" + "       <member priority=\"0\">  \r\n"
				+ "          <callManager>  \r\n" + "             <ports>  \r\n"
				+ "                 <sipPort>5060</sipPort>  \r\n" + "             </ports>  \r\n"
				+ "             <processNodeName>%s</processNodeName>    --------------- IP of Asterisk box \r\n"
				+ "          </callManager>  \r\n" + "       </member>  \r\n" + "    </members>  \r\n"
				+ " </callManagerGroup>  \r\n" + "</devicePool>  \r\n" + "<sipProfile> \r\n"
				+ "  <sipProxies>      \r\n" + "    <backupProxy>USECALLMANAGER</backupProxy>  \r\n"
				+ "    <backupProxyPort>5060</backupProxyPort>  \r\n"
				+ "    <emergencyProxy>USECALLMANAGER</emergencyProxy>  \r\n"
				+ "    <emergencyProxyPort>5060</emergencyProxyPort>  \r\n"
				+ "    <outboundProxy>USECALLMANAGER</outboundProxy>  \r\n"
				+ "    <outboundProxyPort>5060</outboundProxyPort>  \r\n"
				+ "    <registerWithProxy>true</registerWithProxy> \r\n" + "  </sipProxies>  \r\n"
				+ "  <sipCallFeatures> \r\n" + "    <cnfJoinEnabled>true</cnfJoinEnabled>  \r\n"
				+ "    <callForwardURI>x--serviceuri-cfwdall</callForwardURI>  \r\n"
				+ "    <callPickupURI>x-cisco-serviceuri-pickup</callPickupURI>  \r\n"
				+ "    <callPickupListURI>x-cisco-serviceuri-opickup</callPickupListURI>  \r\n"
				+ "    <callPickupGroupURI>x-cisco-serviceuri-gpickup</callPickupGroupURI>  \r\n"
				+ "    <meetMeServiceURI>x-cisco-serviceuri-meetme</meetMeServiceURI>  \r\n"
				+ "    <abbreviatedDialURI>x-cisco-serviceuri-abbrdial</abbreviatedDialURI>  \r\n"
				+ "    <rfc2543Hold>false</rfc2543Hold>  \r\n" + "    <callHoldRingback>2</callHoldRingback>  \r\n"
				+ "    <localCfwdEnable>true</localCfwdEnable>  \r\n"
				+ "    <semiAttendedTransfer>true</semiAttendedTransfer>  \r\n"
				+ "    <anonymousCallBlock>2</anonymousCallBlock>  \r\n"
				+ "    <callerIdBlocking>2</callerIdBlocking>  \r\n" + "    <dndControl>0</dndControl>  \r\n"
				+ "    <remoteCcEnable>true</remoteCcEnable>  \r\n" + " </sipCallFeatures> \r\n" + " <sipStack>  \r\n"
				+ "    <sipInviteRetx>6</sipInviteRetx>  \r\n" + "    <sipRetx>10</sipRetx>  \r\n"
				+ "    <timerInviteExpires>180</timerInviteExpires>  \r\n"
				+ "    <timerRegisterExpires>3600</timerRegisterExpires>  \r\n"
				+ "    <timerRegisterDelta>5</timerRegisterDelta>  \r\n"
				+ "    <timerKeepAliveExpires>120</timerKeepAliveExpires>  \r\n"
				+ "    <timerSubscribeExpires>120</timerSubscribeExpires>  \r\n"
				+ "    <timerSubscribeDelta>5</timerSubscribeDelta>  \r\n" + "    <timerT1>500</timerT1>  \r\n"
				+ "    <timerT2>4000</timerT2>  \r\n" + "    <maxRedirects>70</maxRedirects>  \r\n"
				+ "    <remotePartyID>false</remotePartyID>  \r\n" + "    <userInfo>None</userInfo>  \r\n"
				+ " </sipStack> \r\n" + " <autoAnswerTimer>1</autoAnswerTimer>  \r\n"
				+ " <autoAnswerAltBehavior>false</autoAnswerAltBehavior>  \r\n"
				+ " <autoAnswerOverride>true</autoAnswerOverride>  \r\n"
				+ " <transferOnhookEnabled>false</transferOnhookEnabled>  \r\n" + " <enableVad>false</enableVad> \r\n"
				+ " <preferredCodec>g711ulaw</preferredCodec>  \r\n" + " <dtmfAvtPayload>101</dtmfAvtPayload>  \r\n"
				+ " <dtmfDbLevel>3</dtmfDbLevel>  \r\n" + " <dtmfOutofBand>avt</dtmfOutofBand>  \r\n"
				+ " <alwaysUsePrimeLine>false</alwaysUsePrimeLine>  \r\n"
				+ " <alwaysUsePrimeLineVoiceMail>false</alwaysUsePrimeLineVoiceMail>  \r\n" + " <kpml>3</kpml>\r\n"
				+ " <phoneLabel>Daniel</phoneLabel> \r\n" + " <stutterMsgWaiting>1</stutterMsgWaiting> \r\n"
				+ " <callStats>false</callStats>  \r\n"
				+ " <silentPeriodBetweenCallWaitingBursts>10</silentPeriodBetweenCallWaitingBursts>  \r\n"
				+ " <disableLocalSpeedDialConfig>false</disableLocalSpeedDialConfig> \r\n"
				+ " <startMediaPort>16384</startMediaPort>  \r\n" + " <stopMediaPort>32766</stopMediaPort> \r\n"
				+ " <sipLines> \r\n" + "   <line  \r\n" + "     button=\"1\"> \r\n"
				+ "       <featureID>9</featureID>  \r\n" + "       <featureLabel>%s</featureLabel>  \r\n"
				+ "       <proxy>USECALLMANAGER</proxy>  \r\n" + "       <port>5060</port> \r\n"
				+ "       <name>%s</name> \r\n" + "       <displayName>%s</displayName>  \r\n"
				+ "       <autoAnswer>\r\n" + "          <autoAnswerEnabled>2</autoAnswerEnabled>\r\n"
				+ "       </autoAnswer>  \r\n" + "       <callWaiting>3</callWaiting> \r\n"
				+ "       <authName>%s</authName>  \r\n" + "       <authPassword>%s</authPassword>  \r\n"
				+ "       <sharedLine>false</sharedLine> \r\n"
				+ "       <messageWaitingLampPolicy>1</messageWaitingLampPolicy>  \r\n"
				+ "       <messagesNumber>*98</messagesNumber>  \r\n"
				+ "       <ringSettingIdle>4</ringSettingIdle>  \r\n"
				+ "       <ringSettingActive>5</ringSettingActive> \r\n" + "       <contact>%s</contact>  \r\n"
				+ "       <forwardCallInfoDisplay>  \r\n" + "          <callerName>true</callerName>  \r\n"
				+ "          <callerNumber>false</callerNumber>  \r\n"
				+ "          <redirectedNumber>false</redirectedNumber>  \r\n"
				+ "          <dialedNumber>true</dialedNumber>  \r\n" + "       </forwardCallInfoDisplay>  \r\n"
				+ "    </line>\r\n" + "</sipLines>\r\n"
				+ " <voipControlPort>5061</voipControlPort>  --------------------------- The phones always expect SIP messages on this port\r\n"
				+ " <dscpForAudio>184</dscpForAudio>  \r\n"
				+ " <ringSettingBusyStationPolicy>0</ringSettingBusyStationPolicy>  \r\n"
				+ " <dialTemplate>dialplan.xml</dialTemplate>  \r\n" + "</sipProfile> \r\n" + "<commonProfile>  \r\n"
				+ " <phonePassword></phonePassword>\r\n" + " <backgroundImageAccess>true</backgroundImageAccess>  \r\n"
				+ " <callLogBlfEnabled>2</callLogBlfEnabled>  \r\n" + "</commonProfile> \r\n"
				+ "<loadInformation>CP3905.9-4-1-0</loadInformation>\r\n" + "<vendorConfig> \r\n"
				+ " <disableSpeaker>false</disableSpeaker> \r\n"
				+ " <disableSpeakerAndHeadset>false</disableSpeakerAndHeadset> \r\n" + " <pcPort>0</pcPort> \r\n"
				+ " <settingsAccess>1</settingsAccess>\r\n" + " <garp>1</garp> \r\n"
				+ " <voiceVlanAccess>0</voiceVlanAccess>\r\n" + " <videoCapability>0</videoCapability>  \r\n"
				+ " <autoSelectLineEnable>0</autoSelectLineEnable> \r\n" + "<sshAccess>1</sshAccess>\r\n"
				+ "<sshPort>22</sshPort> \r\n" + "<webAccess>0</webAccess>  \r\n"
				+ " <spanToPCPort>0</spanToPCPort>  \r\n" + " <loggingDisplay>1</loggingDisplay>  \r\n"
				+ " <loadServer></loadServer>  \r\n" + "</vendorConfig> \r\n"
				+ "<versionStamp>1143565489-a3cbf294-7526-4c29-8791-c4fce4ce4c37</versionStamp>\r\n"
				+ "<userLocale> \r\n" + " <name>BR</name> \r\n" + "<uid>1</uid> \r\n" + " <langCode></langCode> \r\n"
				+ "<version></version> \r\n" + " <winCharSet></winCharSet> \r\n" + "</userLocale> \r\n"
				+ "<deviceSecurityMode>1</deviceSecurityMode> \r\n" + "<authenticationURL></authenticationURL>  \r\n"
				+ "<directoryURL></directoryURL>  \r\n" + "<idleURL></idleURL>  \r\n"
				+ "<informationURL></informationURL> \r\n" + "<messagesURL></messagesURL>  \r\n"
				+ "<proxyServerURL></proxyServerURL>  \r\n" + "<servicesURL></servicesURL> \r\n"
				+ "<dscpForSCCPPhoneConfig>96</dscpForSCCPPhoneConfig>  \r\n"
				+ "<dscpForSCCPPhoneServices>0</dscpForSCCPPhoneServices>  \r\n"
				+ "<dscpForCm2Dvce>96</dscpForCm2Dvce>\r\n" + "<transportLayerProtocol>2</transportLayerProtocol>\r\n"
				+ "\r\n" + "<capfAuthMode>0</capfAuthMode>  \r\n" + "<capfList>  \r\n" + " <capf>  \r\n"
				+ "    <phonePort>3804</phonePort>  \r\n" + " </capf>  \r\n" + "</capfList> \r\n"
				+ "<certHash></certHash>  \r\n" + "<encrConfig>false</encrConfig>  \r\n" + "</device>";
	}
}
